### ISSUE TITLE
Enhancement - clickbait headlines

### ISSUE THREAD

**Issue by johndpope** [harperreed/gpt3-persona-bot#5]
Prime GPT-3 to Speak like Any Big Five Personality / 
https://medium.com/@IntuitMachine/priming-gpt-3-to-speak-like-any-big-five-personality-b610f5aca94f

"rewrite in clickbait style"

I'm also interested to cut a james bond / mission impossible / cloak and dagger kind of personality.
Just don't blow my cover / kind of vibe.

https://www.spymuseum.org/education-programs/spy-resources/language-of-espionage/

other personalities worth exploring

Deniro 

Anchorman
Adam Sandler style / goof character

Steve Stifler / American Pie
https://github.com/Celdir/Forgery/blob/ecf56d9791438389816e87b4508fe2f93fbe31f1/imsdb_scenes_dialogs_nov_2015/dialogs/Comedy/americanpie_dialog.txt

Comedy
https://github.com/Celdir/Forgery/tree/ecf56d9791438389816e87b4508fe2f93fbe31f1/imsdb_scenes_dialogs_nov_2015/dialogs/Comedy

**Comment by psychon7** [comment]
how to train it with more personas?

**Comment by johndpope** [comment]
Craft a json file like this
https://github.com/harperreed/gpt3-persona-bot/blob/master/personas/drianmalcolm.json
and you're almost there. gpt3 will extrapolate a persona in the same vein. 
https://github.com/harperreed/gpt3-persona-bot/tree/master/personas
